# Generated by Django 5.2.5 on 2025-08-28 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name="Nom d'hôte")),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Numéro de série')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Fabricant')),
                ('model', models.CharField(max_length=255, verbose_name='Modèle')),
                ('current_user', models.CharField(max_length=255, verbose_name='Utilisateur actuel')),
                ('system_info', models.JSONField(default=dict, verbose_name='Informations système')),
                ('hardware_info', models.JSONField(default=dict, verbose_name='Informations matérielles')),
                ('network_info', models.JSONField(default=dict, verbose_name='Informations réseau')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière vue')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Ordinateur',
                'verbose_name_plural': 'Ordinateurs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('scan', 'Scan complet'), ('change', 'Détection de changement'), ('error', 'Erreur'), ('sync', 'Synchronisation')], max_length=20, verbose_name='Type de log')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(default=dict, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.computer', verbose_name='Ordinateur')),
            ],
            options={
                'verbose_name': "Log d'inventaire",
                'verbose_name_plural': "Logs d'inventaire",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('version', models.CharField(max_length=100, verbose_name='Version')),
                ('publisher', models.CharField(max_length=255, verbose_name='Éditeur')),
                ('install_date', models.CharField(max_length=50, verbose_name="Date d'installation")),
                ('detection_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de détection')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_list', to='inventory.computer', verbose_name='Ordinateur')),
            ],
            options={
                'verbose_name': 'Logiciel',
                'verbose_name_plural': 'Logiciels',
                'ordering': ['name', 'version'],
                'unique_together': {('computer', 'name', 'version')},
            },
        ),
    ]
