# Generated by Django 5.2.5 on 2025-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='install_location',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name="Emplacement d'installation"),
        ),
        migrations.AddField(
            model_name='software',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='software',
            name='uninstall_string',
            field=models.TextField(blank=True, default='', verbose_name='Commande de désinstallation'),
        ),
    ]
